# Generated by Django 4.0.3 on 2022-03-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'middle_name',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('mobile_number', models.CharField(max_length=12, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
