# Generated by Django 4.0.3 on 2022-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('TODO', 'TODO'),
                            ('PENDING', 'PENDING'),
                            ('DISCARDED', 'DISCARDED'),
                            ('DONE', 'DONE'),
                            ('FAILED', 'FAILED'),
                        ],
                        default='TODO',
                        max_length=32,
                    ),
                ),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
