# Generated by Django 4.0.3 on 2022-03-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_sitemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemodel',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
