# Generated by Django 4.0.3 on 2022-03-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_owner_id_sitemodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemodel',
            name='location_coordinates',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
